site_name: 'EZ2ON REBOOT : R 中文 Wiki'
repo_name: clarilotus/ez2on
repo_url: https://github.com/clarilotus/ez2on
copyright: 版权所有 &copy; 2019-2023 Neonovice Co.,LTD. &copy; 2011-2023 SQUARE PIXELS Corp. &ensp;&ensp;由 Mkdocs 及 Material for MkDocs 驱动
extra:
  generator: false
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/170896943/
      name: bilibili @clarilotus
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=9atW8Y9W
      name: 'EZ2ON REBOOT : R - QQ 交流群' 
nav:
  - '首页': index.md
  - '购买指南': purchase/index.md
  - '游戏指南':   
    - '一、主菜单 & 模式': guide/main.md
    - '二、BASIC & STANDARD 自由演奏': guide/freemode/index.md
    - '三、MULTIPLAY 多人演奏': guide/multiplay/index.md
    - '四、COURSE 课题组曲': guide/course/index.md
    - '五、LOUNGE 个人中心': guide/lounge/index.md
    - '六、OPTION 系统选项': guide/option/index.md
  - '歌曲列表': songlist/index.md
    # - '4K BASIC': songlist/4b.md
    # - '5K BASIC': songlist/5b.md
    # - '6K BASIC': songlist/6b.md
    # - '8K BASIC': songlist/8b.md
    # - '4K STANDARD': songlist/4s.md
    # - '5K STANDARD': songlist/5s.md
    # - '6K STANDARD': songlist/6s.md
    # - '8K STANDARD': songlist/8s.md
  - '课题组曲': course/index.md
  - '视觉装备':
    - '系统主题 SYSTEM': equips/theme.md
    - '演奏面板 PANEL': equips/panel.md
    - '演奏音符 NOTE': equips/note.md
    - '判定字体 JUDGE FONT': equips/judge.md
    - '连击字体 COMBO FONT': equips/combo.md
    - '面板背景 PANEL BG': equips/panelbg.md
  # - 'Rating': rating/index.md
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/hero.png
  language: zh
  palette:
    scheme: default
    primary: white
    accent: teal
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.path
    # - navigation.expand
    # - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    # - content.tabs.link
  font:
    text: Noto Sans Simplified Chinese
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left